---
app_domain: 'staging.publishing.service.gov.uk'
app_domain_internal: "staging.govuk-internal.digital"

backup::server::backup_hour: 9

base::shell::shell_prompt_string: 'staging'
base::supported_kernel::enabled: false

cron::daily_hour: 6

environment_ip_prefix: '10.12'

node_class: &node_class
  asset_master:
    apps:
      - asset_env_sync
  backend:
    apps:
      - transition
      - imminence
      - link-checker-api
      - local-links-manager
      - signon
  bouncer:
    apps:
      - bouncer
  cache:
    apps:
      - router
      - publicapi
  content_store:
    apps:
      - content-store
  calculators_frontend:
    apps:
      - calculators
      - calendars
      - finder-frontend
      - licencefinder
      - smartanswers
  ckan:
    apps:
      - ckan
  draft_cache:
    apps:
      - authenticating-proxy
      - router
      - router-api
      - draft-publicapi
  draft_content_store:
    apps:
      - content-store
  draft_frontend:
    apps:
      - collections
      - email-alert-frontend
      - frontend
      - government-frontend
      - manuals-frontend
      - service-manual-frontend
      - smartanswers
      - static
  email_alert_api:
    apps:
      - email-alert-api
      - email-alert-service
  frontend:
    apps:
      - canary-frontend
      - collections
      - email-alert-frontend
      - feedback
      - frontend
      - government-frontend
      - info-frontend
      - manuals-frontend
      - service-manual-frontend
      - static
  mapit:
    apps:
      - mapit
  mirrorer:
    apps:
      - govuk-crawler-worker
  publishing_api:
    apps:
      - publishing-api
  router_backend:
    apps:
      - router-api
  search:
    apps:
      - rummager
  whitehall_backend:
    apps:
      - whitehall
  whitehall_frontend:
    apps:
      - whitehall

govuk::node::s_base::node_apps:
  <<: *node_class

govuk_jenkins::deploy_all_apps::apps_on_nodes:
  <<: *node_class

govuk::apps::asset_manager::aws_s3_bucket_name: 'govuk-assets-staging'
govuk::apps::asset_manager::aws_region: 'eu-west-1'
govuk::apps::ckan::ckan_site_url: 'https://ckan.staging.publishing.service.gov.uk'
govuk::apps::ckan::s3_bucket_name: "datagovuk-staging-ckan-organogram"
govuk::apps::ckan::s3_aws_region_name: "eu-west-1"
govuk::apps::content_data_admin::google_tag_manager_auth: 'xcAlGBhKTIeO6y_JhmEapQ'
govuk::apps::content_data_admin::google_tag_manager_id: 'GTM-NZG8SF2'
govuk::apps::content_data_admin::google_tag_manager_preview: 'env-5'
govuk::apps::content_publisher::aws_s3_bucket: "govuk-staging-content-publisher-activestorage"
govuk::apps::content_publisher::google_tag_manager_auth: "QaRG0YPL6_pwZdxCbyMXPQ"
govuk::apps::content_publisher::google_tag_manager_id: "GTM-NQXC4TG"
govuk::apps::content_publisher::google_tag_manager_preview: "env-5"
govuk::apps::content_store::performance_platform_big_screen_view_url: 'https://performance-platform-big-screen-view-staging.cloudapps.digital'
govuk::apps::content_store::performance_platform_spotlight_url: 'https://performance-platform-spotlight-staging.cloudapps.digital'
govuk::apps::email_alert_api::db::backend_ip_range: '10.12.3.0/24'
govuk::apps::email_alert_api::email_archive_s3_bucket: 'govuk-staging-email-alert-api-archive'
# This shouldn't be enabled at the same time we have carrenza s3 export enabled unless they have separate buckets
govuk::apps::email_alert_api::email_archive_s3_enabled: false
govuk::apps::email_alert_api::govuk_notify_template_id: '2844a647-6bf1-4b01-a25c-569d2cc00849'
govuk::apps::email_alert_api::email_address_override: 'success@simulator.amazonses.com'
govuk::apps::email_alert_api::email_address_override_whitelist_only: true
govuk::apps::email_alert_api::delivery_request_threshold: "3000"
govuk::apps::email_alert_frontend::subscription_management_enabled: true
govuk::apps::hmrc_manuals_api::publish_topics: false
govuk::apps::kibana::logit_environment: b13bfb70-e07a-473b-9903-02e806ebd045
govuk::apps::link_checker_api::govuk_basic_auth_credentials: "%{hiera('http_username')}:%{hiera('http_password')}"
govuk::apps::publicapi::backdrop_host: 'www.staging.performance.service.gov.uk'
govuk::apps::publisher::run_fact_check_fetcher: false
govuk::apps::publisher::fact_check_address_format: 'factcheck+staging-{id}@alphagov.co.uk'
govuk::apps::publishing_api::event_log_aws_bucketname: 'govuk-publishing-api-event-log-staging'
govuk::apps::short_url_manager::instance_name: 'staging'
govuk::apps::signon::instance_name: 'staging'
govuk::apps::static::ga_universal_id: 'UA-26179049-20'
govuk::apps::support_api::pp_data_url: 'https://www.staging.performance.service.gov.uk'
govuk::apps::travel_advice_publisher::enable_email_alerts: true

govuk::deploy::aws_ses_smtp_host: 'email-smtp.eu-west-1.amazonaws.com'
govuk::deploy::config::errbit_environment_name: 'staging'
govuk::deploy::config::licensify_app_domain: 'staging.publishing.service.gov.uk'
govuk::deploy::setup::ssh_keys:
    jenkins_staging_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQDCtuq8uMfbwh7asChk/F/VD5gPnnBD7pLeN1W4iOrkq3KbzdLErzK3W0EpCA2C07JU55egolaO7lDUF6MtmAiGLfHApju5lZ6ziUq+zebEbkwtpLUNop2zp51pZl5/meMEF9pQEcHD46iZGs1sLuZGNzzu12PKvpAHDFK9GPHrYez7asKh4JVCi5DNusOMFUFE+BW8w37zJZ4ksdeZ58w1PTS8+Q65k6MQdWDAUr9BLcsacZ2kzRHsMxP3bd3lljY9HT0lh1qPgwRcWqbfVjB8dAzTxiQHJm0w3xywcx/IUKMSL1WCJV7rZ5nt0XgOfU/cGRXDtRHPvMMrMfKqFGbyTTCjix4Y0k1FD2udXxvv03GjL12qohrsb1JxFv5CdLbV8Yn96IDIjEVKA+1GIwxl0w4TtMVCLqImIMaTD00tdY58fAb2uIy9xSTxu2jKdsEKCcbbC9ipE5lUM/3/kgl06OljBwgAcLgsbbWAHip59E3l6xO+BmW7f7PeepZMRDr15Xwr4RiEu76SQPoRFM5honi7yPLTNwscEgxEjZgKjOkNfVeABeJhJ5rOElAYx7K1bIsW/93DXtTWPDMxGGkiTM279Evy0LJjdVu6XGDmd9qw8usdKjfjASHe9mMFfSXZflHA6VW2o1Zjo40KWHXxJSdPN4bTujpahjd8QOb6Sw=='
    jenkins_production_carrenza: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQCfPjubgzCkZo1aTPlkgeXb1eh3IonRBRptx0qLMCjOV+e+M8uRAT/Xx3ydJYPd7sOgZDyx2xjSGb7Eefau0jSUAcMD1Xd01SXWBQPJRDfPmQLrdbM0xxOFH8nft39uo4Mz6ccZc34xrudL6q/urp732HZHYwltnNnbk9h58n1QIhemRtN3u9RrSSOILqw/F42S6Aj8lZ1v/DGgfc6F5pKyJ7TByHL1RlqwpZHbEjYYuvK0ZJJsKPlyVPbNDsX7UEYWwbpPsFs9LPvCC6epmj+7Lv25bTU8rKK8J3rNWa1FybpWS0VXbF/+mrLjtT0/vwvbwUzsjK6dSUsbEsBEn+cOqomxCYkLjMzUy1+ReYAh6+CjmzutPs1g4OjQRel2ONprhPTEsNUu+oNObnGDOUpzHK10ntAZxguA4QEUmOBBWfxuQhmJO60/b1zedCcc7MR8e9S0y4jtpXa8GBCe40+napArZTW9QXlHLWz+khkYQfO107Q+z1QaLFojdcrHlUfpqAc6DtVJQu7tsBt2vXTn0qq6mU5Eg6UY+X1l/3gWdFS3ZEvCUoGK6bLU3i50jZ1xsFogFFfvSux46S1DYW2Fk8a/2IBBdcQcL1YoM73jiAQgpU8Vs50wtk4mWhK1yBaMYmMAeL7mKFbJla7SjTAwaDdo5uezyrJlbZxqTb/Y3w=='

# Staging never receives requests to bouncer
govuk_cdnlogs::bouncer_monitoring_enabled: false
# Increase the freshness-threshold for govuk logs as traffic is slower
govuk_cdnlogs::warning_cdn_freshness: 86400   # 1 day
govuk_cdnlogs::critical_cdn_freshness: 172800 # 2 days

govuk_containers::terraboard::aws_bucket: 'govuk-terraform-steppingstone-staging'
govuk_containers::terraboard::oauth2_proxy_base_url: 'https://terraboard.staging.govuk.digital'

govuk_crawler::seed_enable: true
govuk_crawler::sync_enable: true
govuk_crawler::targets:
  - 's3://govuk-staging-mirror-1/'

govuk_elasticsearch::dump::run_es_dump_hour: '4'

govuk_jenkins::job_builder::environment: 'staging'

govuk_jenkins::jobs::network_config_deploy::environments:
  - 'carrenza-staging'
  - 'carrenza-staging-dr'
  - 'skyscape-staging'

govuk_jenkins::jobs::search_fetch_analytics_data::skip_page_traffic_load: true
govuk_jenkins::jobs::search_fetch_analytics_data::cron_schedule: '30 8 * * 1-5'

govuk_jenkins::jobs::smokey::environment: staging

govuk_jenkins::jobs::data_sync_complete_staging::signon_domains_to_migrate:
  -
    old: publishing.service.gov.uk
    new: staging.publishing.service.gov.uk
  -
    old: performance.service.gov.uk
    new: staging.performance.service.gov.uk
  -
    old: -production.cloudapps.digital
    new: -staging.cloudapps.digital

govuk_jenkins::jobs::deploy_dns::gce_client_name: 'govuk-dns-deploy'
govuk_jenkins::jobs::deploy_dns::gce_project_id: 'govuk-staging-160211'

govuk_jenkins::ssh_key::public_key: 'AAAAB3NzaC1yc2EAAAADAQABAAACAQDCtuq8uMfbwh7asChk/F/VD5gPnnBD7pLeN1W4iOrkq3KbzdLErzK3W0EpCA2C07JU55egolaO7lDUF6MtmAiGLfHApju5lZ6ziUq+zebEbkwtpLUNop2zp51pZl5/meMEF9pQEcHD46iZGs1sLuZGNzzu12PKvpAHDFK9GPHrYez7asKh4JVCi5DNusOMFUFE+BW8w37zJZ4ksdeZ58w1PTS8+Q65k6MQdWDAUr9BLcsacZ2kzRHsMxP3bd3lljY9HT0lh1qPgwRcWqbfVjB8dAzTxiQHJm0w3xywcx/IUKMSL1WCJV7rZ5nt0XgOfU/cGRXDtRHPvMMrMfKqFGbyTTCjix4Y0k1FD2udXxvv03GjL12qohrsb1JxFv5CdLbV8Yn96IDIjEVKA+1GIwxl0w4TtMVCLqImIMaTD00tdY58fAb2uIy9xSTxu2jKdsEKCcbbC9ipE5lUM/3/kgl06OljBwgAcLgsbbWAHip59E3l6xO+BmW7f7PeepZMRDr15Xwr4RiEu76SQPoRFM5honi7yPLTNwscEgxEjZgKjOkNfVeABeJhJ5rOElAYx7K1bIsW/93DXtTWPDMxGGkiTM279Evy0LJjdVu6XGDmd9qw8usdKjfjASHe9mMFfSXZflHA6VW2o1Zjo40KWHXxJSdPN4bTujpahjd8QOb6Sw=='

govuk_mysql::server::expire_log_days: 1
govuk_mysql::server::innodb_buffer_pool_size_proportion: '0.5'
govuk_mysql::server::slow_query_log: true

govuk::node::s_asset_master::copy_attachments_hour: 7

govuk::node::s_cache::real_ip_header: 'True-Client-Ip'
# The option below can be changed to enable router to run as a container
govuk::node::s_cache::router_as_container: false
govuk::node::s_monitoring::offsite_backups: false

govuk_sudo::sudo_conf:
  deploy_service_postgresql:
    content: 'deploy ALL=NOPASSWD:/etc/init.d/postgresql'

grafana::dashboards::machine_suffix_metrics: '_staging'

licensify::apps::licensify_admin::environment: 'staging'
licensify::apps::licensify::environment: 'staging'
licensify::apps::licensify_feed::environment: 'staging'

monitoring::checks::sidekiq::enable_support_check: false
monitoring::checks::ses::region: 'eu-west-1'
monitoring::checks::rds::region: 'eu-west-1'
monitoring::checks::cache::region: 'eu-west-1'


monitoring::checks::rds::servers:
   - 'postgresql-primary'
   - 'postgresql-standby'
   - 'transition-postgresql-primary'
   - 'transition-postgresql-standby'
   - 'mysql-primary'
   - 'mysql-replica'


# START OF TEMPORARY DEFECT FIX: # Smokey tests are not running correctly due to defects reported in: https://trello.com/c/XzGHhe3l/1629-investigate-cause-of-jenkins-oom-crashes-in-aws-staging-and-production
# monitoring::checks::smokey::environment: 'staging'
# END OF TEMPORARY DEFECT FIX

monitoring::uptime_collector::environment: 'staging'

postfix::smarthost:
  - 'email-smtp.us-east-1.amazonaws.com:587'
  - 'ses-smtp-prod-335357831.us-east-1.elb.amazonaws.com:587'
postfix::rewrite_mail_domain: 'digital.cabinet-office.gov.uk'
postfix::rewrite_mail_list: 'machine.email.carrenza'

router::nginx::robotstxt: |
  User-agent: *
  Disallow: /

nginx::config::stack_network_prefix: '10.12.0'

govuk_datascrubber::ensure: 'latest'
govuk_datascrubber::share_with:
  - '210287912431'     # AWS integration
govuk_datascrubber::s3_export_prefix: 's3://govuk-production-database-backups/scrubbed'

hosts::aws_production::app_domain: 'staging.publishing.service.gov.uk'
hosts::aws_production::ip_api_lb: '10.2.4.254'
hosts::aws_production::ip_backend_lb: '10.2.3.254'
hosts::aws_production::ip_bouncer: '37.26.91.5'
hosts::aws_production::ip_draft_api_lb: '10.2.4.253'
hosts::aws_production::ip_frontend_lb: '10.2.2.254'
hosts::aws_production::licensify_hosts:
  licensify.staging.publishing.service.gov.uk:
    ip: '37.26.91.8'
  licensify-admin.staging.publishing.service.gov.uk:
    ip: '37.26.91.8'

hosts::aws_production::api::hosts:
  api-1:
    ip: '10.2.4.16'
  api-2:
    ip: '10.2.4.17'
  api-lb-1:
    ip: '10.2.4.101'
  api-lb-2:
    ip: '10.2.4.102'
  api-mongo-1:
    ip: '10.2.4.21'
  api-mongo-2:
    ip: '10.2.4.22'
  api-mongo-3:
    ip: '10.2.4.23'
  api-mongo-4:
    ip: '10.2.12.21'
  api-redis-1:
    ip: '10.2.4.29'
  content-store-1:
    ip: '10.2.4.11'
  content-store-2:
    ip: '10.2.4.12'
  content-store-3:
    ip: '10.2.4.13'
  draft-content-store-1:
    ip: '10.2.4.200'
  draft-content-store-2:
    ip: '10.2.4.201'
  mapit-1:
    ip: '10.2.4.60'
  mapit-2:
    ip: '10.2.4.61'
  performance-mongo-1:
    ip: '10.2.4.31'
  performance-mongo-2:
    ip: '10.2.4.32'
  performance-mongo-3:
    ip: '10.2.4.33'
  performance-mongo-4:
    ip: '10.2.12.31'
  rummager-elasticsearch-1:
    ip: '10.2.4.55'
  rummager-elasticsearch-2:
    ip: '10.2.4.56'
  rummager-elasticsearch-3:
    ip: '10.2.4.57'
  search-1:
    ip: '10.2.4.4'
  search-2:
    ip: '10.2.4.5'
  search-3:
    ip: '10.2.4.6'

hosts::aws_production::backend::hosts:
  asset-master-1:
    ip: '10.2.3.20'
    legacy_aliases:
      - 'asset-master-1.staging.publishing.service.gov.uk'
      - 'asset-master'
      - 'asset-master.staging.publishing.service.gov.uk'
  asset-slave-1:
    ip: '10.2.3.21'
    legacy_aliases:
      - 'asset-slave-1.staging.publishing.service.gov.uk'
      - 'asset-slave'
      - 'asset-slave.staging.publishing.service.gov.uk'
  asset-slave-2:
    ip: '10.2.11.21'
  ckan-1:
    ip: '10.2.3.120'
  docker-backend-1:
    ip: '10.2.3.111'
  docker-backend-2:
    ip: '10.2.3.112'
  elasticsearch-1:
    ip: '10.2.3.15'
  elasticsearch-2:
    ip: '10.2.3.16'
  elasticsearch-3:
    ip: '10.2.3.17'
  email-alert-api-1:
    ip: '10.2.3.40'
  email-alert-api-2:
    ip: '10.2.3.41'
  email-alert-api-3:
    ip: '10.2.3.42'
  publishing-api-1:
    ip: '10.2.3.45'
  publishing-api-2:
    ip: '10.2.3.46'
  publishing-api-3:
    ip: '10.2.3.47'
  rabbitmq-1:
    ip: '10.2.3.70'
  rabbitmq-2:
    ip: '10.2.3.71'
  rabbitmq-3:
    ip: '10.2.3.72'
  whitehall-backend-1:
    ip: '10.2.3.25'
  whitehall-backend-2:
    ip: '10.2.3.26'
  whitehall-backend-3:
    ip: '10.2.3.27'
  whitehall-backend-4:
    ip: '10.2.3.28'

hosts::aws_production::backend::app_hostnames:
  - 'asset-manager'
  - 'canary-backend'
  - 'ckan'
  - 'collections-publisher'
  - 'contacts-admin'
  - 'content-audit-tool'
  - 'content-data-admin'
  - 'content-performance-manager'
  - 'content-publisher'
  - 'content-tagger'
  - 'docs'
  - 'email-alert-api'
  - 'email-alert-api-public'
  - 'event-store'
  - 'hmrc-manuals-api'
  - 'kibana'
  - 'maslow'
  - 'manuals-publisher'
  - 'publisher'
  - 'publishing-api'
  - 'search-admin'
  - 'service-manual-publisher'
  - 'short-url-manager'
  - 'signon'
  - 'specialist-publisher'
  - 'specialist-publisher-rebuild'
  - 'specialist-publisher-rebuild-standalone'
  - 'support'
  - 'support-api'
  - 'travel-advice-publisher'
  - 'whitehall-admin'


hosts::aws_production::frontend::hosts:
  calculators-frontend-1:
    ip: '10.2.2.11'
  calculators-frontend-2:
    ip: '10.2.2.12'
  calculators-frontend-3:
    ip: '10.2.2.13'
  frontend-1:
    ip: '10.2.2.2'
  frontend-2:
    ip: '10.2.2.3'
  frontend-3:
    ip: '10.2.2.4'
  draft-frontend-1:
    ip: '10.2.2.200'
  draft-frontend-2:
    ip: '10.2.2.201'
  whitehall-frontend-1:
    ip: '10.2.2.5'
  whitehall-frontend-2:
    ip: '10.2.2.6'
  whitehall-frontend-3:
    ip: '10.2.2.10'
  frontend-lb-1:
    ip: '10.2.2.101'
  frontend-lb-2:
    ip: '10.2.2.102'

hosts::aws_production::management::hosts:
  backup-1:
    ip: '10.2.0.50'
  apt-1:
    ip: '10.2.0.75'
    service_aliases:
      - 'apt'
      - 'gemstash'
  docker-management-1:
    ip: '10.2.0.80'
    service_aliases:
      - 'etcd'
  mirrorer-1:
    ip: '10.2.0.128'

hosts::aws_production::router::hosts:
  cache-1:
    ip: '10.2.1.2'
  cache-2:
    ip: '10.2.1.3'
  cache-3:
    ip: '10.2.1.4'
  draft-cache-1:
    ip: '10.2.1.200'
  draft-cache-2:
    ip: '10.2.1.201'
  router-backend-1:
    ip: '10.2.1.10'
  router-backend-2:
    ip: '10.2.1.11'
  router-backend-3:
    ip: '10.2.1.12'
  router-backend-4:
    ip: '10.2.9.10'
  cache:
    ip: '10.2.1.254'
    legacy_aliases:
      - 'cache'
      - "www.%{hiera('hosts::aws_production::app_domain')}"
      - "www-origin.%{hiera('hosts::aws_production::app_domain')}"
      - "assets-origin.%{hiera('hosts::aws_production::app_domain')}"
    service_aliases:
      - 'cache'
      - 'router'
  router-backend-internal-lb:
    ip: '10.2.1.253'
    legacy_aliases:
      - "router-api.%{hiera('hosts::aws_production::app_domain')}"
  draft-cache-internal-lb:
    ip: '10.2.1.252'
    legacy_aliases:
      - "draft-router-api.%{hiera('hosts::aws_production::app_domain')}"
      - "draft-publicapi.%{hiera('hosts::aws_production::app_domain')}"
